language: node_js
services:
  - docker
node_js:
  - "10"
  - "12"
env:
  global:
    - DEV_BRANCH=dev
    - RELEASE_BRANCH=release
    - POST_RELEASE_BRANCH=main
    - RELEASE_MESSAGE=release
cache:
  npm: true
  directories:
    - "node_modules"
  override:
    - npx cypress verify
script:
  - npm run build
jobs:
  include:
    - stage: lint
      name: linter
      script: npm run lint:all
